language: go
go:
 - 1.8.3
sudo: required
services:
 - docker
env:
    - TEST_TARGET=unit-test
    - TEST_TARGET=behave
    - TEST_TARGET=node-sdk-unit-tests

install:
- docker build -t blog .
- docker run -d -p 10.1.3.205:22 --name tjwangduo

before_script:
- pip install -r requirements.txt
- pip install mock
- pip install requests
- pip install feedparser

script:
- docker ps | grep -q blog
- go tests.go
