language: go
go:
 - 1.7
 - 1.8
 
 services:
- docker

git:
  submodules: false
  
install:
      - npm install
 
script:
- docker ps | grep -q blog
     $ git add .travis.yml 
     $ git commit -m "Adding docker build steps to Travis"
     [building-docker-with-travis 2ad7a43] Adding docker build steps to Travis
     1 file changed, 10 insertions(+), 32 deletions(-)
     rewrite .travis.yml (72%)
     $ git push origin building-docker-with-travis

dist: trusty
test:
     - npm run test

